### ISSUE TITLE
Can't contain VertexBuffers in fixed length arrays

### ISSUE THREAD

**Issue by adudney** [tomaka/glium#421] opened 2015-01-31 05:51 UTC
Sample code here: https://gist.github.com/adudney/fa7c83a7ae79bc8a0513

As shown on line 21, I get a compile error trying to create a fixed length array of Options containing VertexBuffers. I'm attempting to use Glium in my app that uses runtime mesh generation. My vertex data is mostly procedurally generated, which means some of it may not exist if the model for that object doesn't exist. (Thus the Options)

Creating a Vec and putting items in using a for loop and then using as_slice gives a type error because it can't cast &[T] to [T;16]

I hope there's a simple solution that I just don't know about due to my relative immaturity in using Rust.

**Comment by tomaka** [comment] 2015-01-31 07:48
The problem is that when you write `[None; SIZE]`, you create a `None` and then Rust wants to copy it `SIZE - 1` times in order to fill the array.

But the `Option<Mesh>` type doesn't implement `Copy` because `VertexBuffer` doesn't implement it, so it prints this error, even though it could theoretically copy the `None`.

You should use a `Vec<Mesh>` instead of an array like this, it's far simpler.

**Comment by adudney** [comment] 2015-01-31 17:14
Hm. I suppose that'd work, I would prefer a fixed size array, but I can see why they don't implement copy.

**Comment by tomaka** [comment] 2015-02-01 19:56
Closing as it's not a glium-related issue but more a Rust-related issue.

**Closed by tomaka** 2015-02-01 19:56 UTC
