### ISSUE TITLE
glutin window cannot be closed

### ISSUE THREAD

**Issue by seifertm** [tomaka/glium#992] opened 2015-06-16 11:09 UTC
The following code creates a window that cannot be closed:

    extern crate glium;

    fn main() {
        use glium::DisplayBuild;
        let display = glium::glutin::WindowBuilder::new().build_glium().unwrap();
        
        loop {
            if display.is_closed() {
                break;
            }
        }
    }

I cannot close the created window by clicking on the close button, nor by Hitting Alt+F4. The example code in tutorial 1 (getting started) exhibits the same issue.

The example was run under Gentoo Linux with the KDE Plasma 5.3 desktop using the kwin-5.3.1 window manager.

**Comment by tomaka** [comment] 2015-06-16 12:13
Closing as a duplicate of #831
But thanks for reporting! (don't hesitate to report any other issue you may find)

**Closed by tomaka** 2015-06-16 12:13 UTC

**Comment by lspitzner** [comment] 2016-12-05 17:05
hi! even with the solution in #831 it seems the window is not actually closed until the app halts. There should be a way to properly dispose of the window (instead of just hiding, which requires the user to keep track of the window instance - or is that a singleton anyways?)

**Comment by fschutt** [comment] 2018-02-01 12:43
@tomaka There is still no way of closing a window without exiting the app at the same time.
