### ISSUE TITLE
OpenGL not loaded correctly on OSX

### ISSUE THREAD

**Issue by TyOverby** [tomaka/glium#336] opened 2015-01-20 19:01 UTC
I've seen this complaint on `#rust-gamedev`, but I didn't see a bug for it, so here's what I get on my late-2014 macbook pro.

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OpenGlError("OpenGL implementation doesn\'t support vertex array objects\nOpenGL implementation doesn\'t support sampler objects")', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:742
```

**Comment by tomaka** [comment] 2015-01-20 19:10
Can be fixed by adding `.with_gl_version((3, 1))` before creating the display.

**Comment by palango** [comment] 2015-01-20 19:39
Think I have the same problem on OS X 10.10.1. After adding what you proposed the error looks like that
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("ERROR: 0:2: \'\' :  version \'110\' is not supported\nERROR: 0:3: \'\' :  #version required and missing.\nERROR: 0:4: \'attribute\' : syntax error: syntax error\n")', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:744
```
The according code:
```
    let display = glutin::WindowBuilder::new()
        .with_dimensions(1024, 768)
        .with_title(format!("Hello world"))
        .with_gl_version((3, 3))
        .build_glium()
        .unwrap();
```

**Comment by tomaka** [comment] 2015-01-20 19:48
Could you try `(3, 2)` instead?

Basically, the problem is this:

- On OS/X, you only have access to three versions of OpenGL: "legacy", 3.2 and 4.1.
- Contrary to Windows and Linux, OS/X doesn't support "compatibility" contexts.
- With the "legacy" context (which is the default), you get @TyOverby's error.
- With the 4.1 context (which is what you get with `(3, 3)`), you get @palango's error. This is because the shader version 110 has been removed since version 3.3.
- With the 3.2 context, I don't know.

**Comment by palango** [comment] 2015-01-20 19:52
Seems to be the same error. Kind of strange.
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("ERROR: 0:2: \'\' :  version \'110\' is not supported\nERROR: 0:3: \'\' :  #version required and missing.\nERROR: 0:4: \'attribute\' : syntax error: syntax error\n")', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:744
An unknown error occurred
```

**Comment by TyOverby** [comment] 2015-01-20 20:07
Is there any benefit to auto-detecting gl capabilities.

**Comment by tomaka** [comment] 2015-01-20 20:09
Vertex array objects are used internally by Glium. If I don't print an Err at initialization, you just get GL errors and nothing works.

**Comment by tomaka** [comment] 2015-01-20 20:30
I think I'll just support this legacy context.

**Comment by tomaka** [comment] 2015-01-21 05:40
Alternatively there's the GL_APPLE_vertex_array_object extension. That's probably the way to go.

**Comment by tomaka** [comment] 2015-01-21 06:11
Could one of you clone the `solve-apple-issues` branch, then set the `TRAVIS` environment variable to `1`, and see if the triangle and image examples work?

**Comment by tomaka** [comment] 2015-01-21 07:00
I merged the two changes in master. Let me know if this is fixed.

**Comment by palango** [comment] 2015-01-21 07:23
The triangle and image examples work fine now without setting the GL version. Great work!

However the mouse shows the pointer of being busy and it it not possible to close the window with the mouse, just by killing it in the command line.

**Comment by camjackson** [comment] 2015-01-21 09:29
As I mentioned in #rust-gamedev earlier, I'm getting the same thing - rendering is OK but the app is non-responsive. I tried using `display.poll_events` but no events are coming through.

Seems to me like this might be more of an issue in glutin, rather than glium?

**Comment by camjackson** [comment] 2015-01-21 10:24
I just ran the window example in glutin, and everything looks fine there, so maybe it's a glium issue after all.

**Comment by tomaka** [comment] 2015-01-21 10:40
There are two differences I can see: glium uses `poll_events` while the window example uses `wait_events`, and glium polls events in a different thread.

**Comment by camjackson** [comment] 2015-01-21 12:31
Might be a little bit out of my depth here, but... Aren't the 2 examples very different? The glium triangle example constructs a glium `Display`, and calls its `poll_events`, which gets events from a `Receiver<glutin::Event>>. Whereas the glutin window example obviously uses glutin directly to build the `Window` and examine events.

**Comment by camjackson** [comment] 2015-01-21 12:34
FWIW, using using `poll_events` in glutin works fine, but there's no `wait_events` in glium for me to test with.

**Comment by TyOverby** [comment] 2015-01-21 21:28
I'm getting the same thing. Without `with_gl_version`, stuff gets drawn to the screen, but I get the beachball cursor and I don't get any events through.

**Comment by adudney** [comment] 2015-02-01 09:08
I'm getting the same beachball no matter what GL version I tell Glium to use.

One thing to note, all AppKit calls must be done on the main thread, I'm not sure how Glium/Glutin handles the event polling, but if it's doing it on a background thread as it seems to be, that won't work. (AppKit does weird things when called from a background thread)

**Comment by tomaka** [comment] 2015-02-01 21:54
I'll close this in favor of #425 since this one was originally about the version being incompatible.

**Closed by tomaka** 2015-02-01 21:54 UTC
Labels: os/x, T-enhancement
