### ISSUE TITLE
fullscreen example panics when I do what I'm told

### ISSUE THREAD

**Issue by Kingsquee** [tomaka/glium#977] opened 2015-06-12 06:32 UTC
Fedora 21
Gallium 0.4 on AMD RV620
OpenGL 3.3 (Core Profile) Mesa 10.4.7

```$ ./fullscreen ```
```Press Enter to switch fullscreen mode```
>I press enter.

```thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: BackendCreationError(OsError("Could not find a suitable graphics mode"))', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729```

**Comment by Esption** [comment] 2015-06-12 13:56
`cargo run --example fullscreen` fails for me too, so not just you.

The error seems to say that glutin isn't able to make the fullscreen mode properly.

```
 $ cargo run --example fullscreen
   Compiling glium v0.5.3 (file:///home/esption/git-clones/glium)
     Running `target/debug/examples/fullscreen`
Press Enter to switch fullscreen mode
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: BackendCreationError(OsError("Could not find a suitable graphics mode"))', /var/tmp/portage/dev-lang/rust-1.0.0_beta3/work/rustc-1.0.0-beta.3/src/libcore/result.rs:729
An unknown error occurred
```

**Comment by tomaka** [comment] 2015-06-26 15:16
Will probably be fixed by https://github.com/tomaka/glutin/pull/504

**Comment by tomaka** [comment] 2015-06-27 20:01
I published a new version of glutin and this bug should be fixed.

**Closed** 2015-06-27 20:01 UTC
Labels: T-bug

**Comment by Gankro** [comment] 2015-08-25 01:11
This bug seems to be showing up in `pistoncore-glutin_window` using glutin 0.3.5.

A simple reproduction is just adding `.fullscreen(true)` to line 13 of this example: https://github.com/PistonDevelopers/piston-examples/blob/master/src/paint.rs

**Comment by tomaka** [comment] 2015-08-25 06:33
@Gankro Please open an issue in the glutin repo!
