### ISSUE TITLE
glium rendering thread panicked: GL_INVALID_OPERATION <levels> is out of range

### ISSUE THREAD

**Issue by andrewrk** [tomaka/glium#419] opened 2015-01-30 23:32 UTC
Code to reproduce this bug: https://github.com/andrewrk/genesis/tree/glium-bugreport-1

```
thread 'glium rendering thread' panicked at 'Debug message with high or medium severity: `GL_INVALID_OPERATION error generated. <levels> is out of range.`.
Please report this error: https://github.com/tomaka/glium/issues', /home/andy/.cargo/git/checkouts/glium-cee1c79709e4d1bd/master/src/lib.rs:1656
[Switching to Thread 0x7fffea3b3700 (LWP 30903)]

Breakpoint 1, 0x00007ffff7695c80 in rust_panic () from /usr/local/lib/libstd-4e7c5e5c.so
(gdb) bt
#0  0x00007ffff7695c80 in rust_panic () from /usr/local/lib/libstd-4e7c5e5c.so
#1  0x00007ffff7602837 in rt::unwind::begin_unwind_inner::haa1ac937607e9179jZA ()
   from /usr/local/lib/libstd-4e7c5e5c.so
#2  0x00007ffff7602e6b in rt::unwind::begin_unwind_fmt::ha84452bff441c4ffPXA ()
   from /usr/local/lib/libstd-4e7c5e5c.so
#3  0x00005555557a8266 in glium::Display::init_debug_callback::callback_wrapper (source=33350, 
    ty=33356, id=1282, severity=37190, _length=63, 
    message=0x7ffff55024c0 "GL_INVALID_OPERATION error generated. <levels> is out of range.", 
    user_param=0x0) at <std macros>:8
#4  0x00005555557a7e7a in Display::init_debug_callback::callback_wrapper::hc17a35f295b4b53ehe8 ()
#5  0x00007ffff3f1b738 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#6  0x00007ffff3f1bdc0 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#7  0x00007ffff3f1bfa2 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#8  0x00007ffff3fdd9f3 in ?? () from /usr/lib/nvidia-331-updates/libnvidia-glcore.so.331.113
#9  0x00005555556b97b2 in glium::gl::Gl::TexStorage2D (self=0x7fffea3acc88, target=3553, levels=33, 
    internalformat=32856, width=219, height=-15)
    at target/build/glium-af9a1675d224f665/out/gl_bindings.rs:28631
#10 0x00005555556b8bb4 in fnfn (ctxt=...)
    at /home/andy/.cargo/git/checkouts/glium-cee1c79709e4d1bd/master/src/texture/tex_impl.rs:180
#11 0x00005555556b7ee4 in thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h5704591827720577128 ()
#12 0x00005555556d1c41 in fnfn ()
    at /home/andy/.cargo/git/checkouts/glium-cee1c79709e4d1bd/master/src/context/glutin_context.rs:79
#13 0x00005555556d13a4 in thunk::Thunk$LT$$LP$$RP$$C$$u{20}R$GT$::new::closure.46000 ()
#14 0x00005555556d12a8 in thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h1279727143568275290 ()
#15 0x00005555556cef1d in thunk::Thunk$LT$A$C$$u{20}R$GT$::invoke::h380524902953828695 ()
#16 0x00005555556cfc49 in thread::Builder::spawn_inner::closure.45967 ()
---Type <return> to continue, or q <return> to quit---
#17 0x00005555556cfbdf in rt::unwind::try::try_fn::__rust_abi::h16965195207491155524 ()
#18 0x00005555556cfb7a in rt::unwind::try::try_fn::h16965195207491155524 ()
#19 0x00007ffff7701329 in rust_try_inner () from /usr/local/lib/libstd-4e7c5e5c.so
#20 0x00007ffff7701316 in rust_try () from /usr/local/lib/libstd-4e7c5e5c.so
#21 0x00005555556cf060 in rt::unwind::try::h13507374188093526309 ()
#22 0x00005555556cde7b in thread::Builder::spawn_inner::closure.45833 ()
#23 0x00005555556d0d24 in thunk::Thunk$LT$$LP$$RP$$C$$u{20}R$GT$::new::closure.45990 ()
#24 0x00005555556d0c42 in thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h1714263383997149003 ()
#25 0x00007ffff7682806 in sys::thread::thread_start::he52b8673a3629881W3w ()
   from /usr/local/lib/libstd-4e7c5e5c.so
#26 0x00007ffff73390a5 in start_thread (arg=0x7fffea3b3700) at pthread_create.c:309
#27 0x00007ffff5c1788d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by andrewrk** [comment] 2015-01-30 23:50
I believe this is due to texture height being negative.

**Comment by tomaka** [comment] 2015-01-31 07:53
Duplicate of #74

**Closed by tomaka** 2015-01-31 07:53 UTC
Labels: T-bug
